### ISSUE TITLE
Specify the Location of the OCaml Binary for `checker.py`

### ISSUE THREAD

**Issue by engineerjoe440** [jubnzv/iec-checker#5]
## Contribution Concept:
During some early testing, I realized that the OCaml file would need to be placed in a specific location for the Python scripts to be able to reference it. From poking around in the .py files, it looks like the default location for the binary is: `../output/bin/iec_checker` (just like what's shown in the usage example of the [main README](https://github.com/jubnzv/iec-checker#usage-examples) ). It seems like this could be added as an optional argument to the Python script to allow the user to specify a file path to the binary.

I think that with this added argument, it would be pretty easy for a user to execute:
```shell
$ python checker.py <files> -b <path/to/my/copy/of/the/binary/file>
```
or
```shell
$ python checker.py <files> --binary <path/to/my/copy/of/the/binary/file>
```

What do you think?

If you're not opposed, I could implement the feature in a pull request for your review. I would imagine it wouldn't take much time to perform. Would you be open to such a contribution?

**Comment by jubnzv** [comment]
Yes, that's a good point. Your contribution are welcome.
I like the idea of passing the file path to the binary through the command line argument. Expect for the changes in the [checker.py](https://github.com/jubnzv/iec-checker/blob/master/checker.py) and [core.py](https://github.com/jubnzv/iec-checker/blob/master/src/python/core.py) this will require tweaking the test suite that also calls the functions from `core.py` to run tests.

**Comment by engineerjoe440** [comment]
Forgive me for not starting on this a little sooner, but I've just made a new branch, and I'm going to open a PR in just a moment! Thanks, so much for your willingness to allow contributions! Please let me know if I've made any styling choices that you would like changed, or anything else! :)
